import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // return (
  //   <html lang="en">
  //     <body className={inter.className}>{children}</body>
  //   </html>
  // );
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <a href="/page1">Page 1</a> | <a href="/page2">Page 2</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
